<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPBYMINW5982" name="Multtest" tests="6" failures="2" timestamp="20 Jan 2017 09:14:51 GMT" time="2.064" errors="0">
  <testcase name="testDiv" time="0.009" classname="com.epam.testngtask.CalculatorTest"/>
  <testcase name="testMult" time="0.008" classname="com.epam.testngtask.Multtest">
    <failure type="java.lang.AssertionError" message="expected [17] but found [16]">
      <![CDATA[java.lang.AssertionError: expected [17] but found [16]
	at com.epam.testngtask.Multtest.testMult(Multtest.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testMult -->
  <testcase name="sumCheck" time="0.027" classname="com.epam.testngtask.CalculatorTest"/>
  <testcase name="sumCheck" time="0.0" classname="com.epam.testngtask.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [-90] but found [110]">
      <![CDATA[java.lang.AssertionError: expected [-90] but found [110]
	at com.epam.testngtask.CalculatorTest.sumCheck(CalculatorTest.java:88)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- sumCheck -->
  <testcase name="testSin" time="2.036" classname="com.epam.testngtask.CalculatorTest"/>
  <testcase name="testSqrt" time="2.023" classname="com.epam.testngtask.CalculatorTest"/>
</testsuite> <!-- Multtest -->
